### ISSUE TITLE
Filter Image Service by Values

### ISSUE THREAD

**Issue by simongis** [Esri/WAB-Image-Services-Widgets#12]
I have a simple image service, served up from ArcGIS Server 10.5. ([REST details](https://pastebin.com/9Y3i7rCp)) from a Mosaic Dataset.  

I am just interested in the one dataset within this Mosaic Dataset which has a value between 0-100.

![screenshot](https://geonet.esri.com/servlet/JiveServlet/downloadImage/2-694595-357483/1.png)

I want to allow the user within AppBuilder to filter the raster based upon them choosing a min and max value to display (e.g. >75; 40-80; etc.).  Ideally dynamically client-side like [this JS sample,](https://developers.arcgis.com/javascript/3/jssamples/layers_raster.html) but also happy for a server side option.
 
I have the Web AppBuilder Developer Edition 2.4 installed with all of the Imagery widgets installed, and was hoping there might be something in here that would help, but struggling to get any of the widgets to work with my image service. 
 
Can someone suggest a way to allow a user to filter an image service based upon the pixel value?

**Comment by kushu493** [comment]
Hi Simon,

Currently  none of the widgets in this repo support this feature. But we are planning to release a client side Mask (Filter) widget in future.

Regards,

Kushagra Patel

**Comment by TraceyVG** [comment]
Kushgara, 

Would that filter allow clients to filter on any field they choose?  For example, could they choose to display only oblique images?

And do you have any approximation for when this widget may be released?

Thank you, 

Tracey Van Gundy

**Comment by kushu493** [comment]
Hi Tracey,

The widget that you are looking for is ISImageSelector. It has been released with WABIS 2.0 - Beta.
Link - https://github.com/Esri/WAB-Image-Services-Widgets/tree/WABIS-2.0-Beta

Regards,

Kushagra Patel

**Comment by TraceyVG** [comment]
Hello Kushgara,

Thank you for the link to the new Beta-version WABIS 2.0.  I have downloaded them and added them to our WAB.  I am working on a project with Roslyn Dunn from ESRI Redlands, whom  I believe contacted you last week as well.  80% of my job is now centered on testing and documenting WABIS widgets on imagery services created by Roslyn, in order to see if they will meet the needs of our project. So you will probably be hearing from me again.

I appreciate your help.

Tracey Van Gundy
