### ISSUE TITLE
Image Date glitches?

### ISSUE THREAD

**Issue by TraceyVG** [Esri/WAB-Image-Services-Widgets#16]
I'm testing the IS ImageDate widget in two Apps: one using the ESRI WebMap created for WAB-IS, and one using our own imagery services.

The only documentation I have found about the IS Image Date widget says that it "shows the date range for the visible rasters, for the current AOI, on the primary layer and the secondary layer."  It seems that date **range** implies more than one date, though this widget never seems to display anything but a single date, presumable the acquisition date of the primary layer at the center of the display.

When I pan or zoom to center on another image in the mosaic dataset, the new date displays.  But if I use a bookmark to zoom to another area it does not, which I assume is because I have switched to the bookmark widget.  If I go back to the ImageDate widget after using the bookmark, it works again.  However, if I use the Image Layers widget to swap the primary and secondary layers, and THEN try to use the ImageDate widget, it does not work until I refresh the entire page.  If I use  the Layer List widget to adjust the transparency of the primary layer, allowing the secondary layer to display beneath it, when I click on ImageDate, It sometimes works; other times, I get a createwidget  error.  It may be a function of how many other widgets I use in between.

At any rate, aside from the times when the widget just stops working, is this how it should be functioning?  With only a single date displayed at any given time, rather than a range?

**Comment by kushu493** [comment]
IS ImageDate will only show a single date. Range feature has been removed from the widget. It shows only the current date of the primary layer or secondary layer (depending on visibility).

IS ImageDate is an off panel widget (like scalebar, coordinate, search widget in web appbuilder). Therefore, it is advised to load it as a on screen widget.  Below is an image which shows where you can load the on screen widgets. After loading the widget here, make the openAtStart property true.
![image](https://user-images.githubusercontent.com/11013183/27603360-f1252562-5b86-11e7-890c-c9161170f0e8.png)


Avoid loading the widget in header controller panel. This is the header controller panel where you have currently loaded the IS ImageDate widget.
![image](https://user-images.githubusercontent.com/11013183/27603518-5c7f5c60-5b87-11e7-904c-6949b628fc51.png)

**Comment by TraceyVG** [comment]
I actually have the IS ImageDate widget loaded as an onscreen widget, not in the header controller panel.  I did not have it set to open at start, though.  I will try that. 

But you raised another good point.  Where can I learn more about which widgets are best loaded in which place?

I am currently using these onscreen widgets: 
IS ImageDate
Bookmark
Swipe
AddData

And I have the following widgets loaded in the header controller panel:
IS Layers
IS TimeFilter
IS TimeFilterProfile
IS ImageSelector

Do I need to change any of these to improve performance?

Thank you for your help; as you can see, I am fairly new to WebAppBuilder, as well as github, and I appreciate the resources being made available.

**Comment by kushu493** [comment]
Web appbuilder doc -https://developers.arcgis.com/web-appbuilder/guide/xt-welcome.htm

Please don't use IS TimeFilter and IS TimeFilterProfile. IS ImageSelector is an advanced version of IS TimeFilter and if you want profile please use IS Profile instead of IS TimeFilterProfile.

IS TimeFilter and IS TimeFilterProfile will soon be deprecated. It is advised to use widgets which are available in WABIS 2.0 - Beta.

You can also add IS ImageDate widget as an default widget of the theme. You see every theme has some default widgets which are already present in theme. So when you select theme they are automatically loaded in the app. You will see these widget here 
![image](https://user-images.githubusercontent.com/11013183/27604725-3bf1ba84-5b8b-11e7-9a8e-9f404e2ace78.png)

These are widgets which are available with the theme. So you can add IS ImageDate here as well. in your scenario its best if you add the widget here. 
To add the widget here you will have to modify the themes available in web appbuilder. You can learn about how to create a theme from here - https://developers.arcgis.com/web-appbuilder/guide/create-a-theme.htm
This will help you to understand the web appbuilder in detail and after going through these docs you can modify current themes or create new themes.

**Comment by TraceyVG** [comment]
Thank you Kushagra; that was very helpful information.
