### ISSUE TITLE
ISExport widget : getUTMZones for non-projectable to Mercator coordinate system

### ISSUE THREAD

**Issue by Biboba** [Esri/WAB-Image-Services-Widgets#27]
Hello,

I noticed a typo in ISExport widget:
https://github.com/Esri/WAB-Image-Services-Widgets/blob/529161c2764cdf6e9de9f0e098ce3e73ecda2dbb/imagery_widgets/ISExport/Widget.js#L290

Also when working with a coordinate system that cannot be projected to Mercator, the UTM zones computation code would fail as mapCenter would be undefined.

**Comment by kushu493** [comment]
Hi Biboba,

Thank you for finding out this issue. I have made the required changes to make it work for all coordinate systems. If projection from one coordinate system to Mercator can be done client side, then client side function is called, otherwise a projection request is made (server). This way it will work for all coordinate systems.
I am not merging your code as there are lot of other changes also.

Thank You.
