### ISSUE TITLE
IS Layers widget appears to rename layerids which causes issues with other widgets

### ISSUE THREAD

**Issue by sirws** [Esri/WAB-Image-Services-Widgets#7]
I am using the filter widget which works off of layerids from the webmap.  As soon as I open the IS Layers widget, the layer ids of the image layers get modified to secondaryLayer and primaryLayer.

You can test this by going to: http://nwdemo1.esri.com/lidarexplorer2/

Open the filter widget and apply a filter on the DSM's
![image](https://cloud.githubusercontent.com/assets/793576/17560057/779a76b0-5ed5-11e6-9959-233c4ae445cc.png)
At this point, it should work.  Then open the ISLayers widget:
![image](https://cloud.githubusercontent.com/assets/793576/17560088/95dccee8-5ed5-11e6-983b-6e95ee32e0ca.png)

Now, the filters break, especially after swapping the primary and secondary layer.  This is because the filter widget is configured based on the layerids, and they are being modified by WABIS.  Just FYI, here is the config for the filter widget:

```
{
  "filters": [
    {
      "layerId": "Master_Mosaic_DTM_4318",
      "url": "http://52.8.111.163/arcgis/rest/services/Master_Mosaic_DTM/ImageServer",
      "name": "All Washington DTMs",
      "filter": {
        "logicalOperator": "AND",
        "parts": [
          {
            "fieldObj": {
              "name": "ProjectID",
              "label": "Project Name",
              "shortType": "string",
              "type": "esriFieldTypeString"
            },
            "operator": "stringOperatorIs",
            "valueObj": {
              "isValid": true,
              "type": "unique",
              "value": ""
            },
            "interactiveObj": {
              "prompt": "Select a project below to view",
              "hint": "Select from list"
            },
            "caseSensitive": false
          }
        ],
        "expr": ""
      },
      "icon": ""
    },
    {
      "layerId": "Master_Mosaic_Dataset_DSM_3150",
      "url": "http://52.8.111.163/arcgis/rest/services/Master_Mosaic_Dataset_DSM/ImageServer",
      "name": "All Washington DSMs",
      "filter": {
        "logicalOperator": "AND",
        "parts": [
          {
            "fieldObj": {
              "name": "ProjectID",
              "label": "Project Name",
              "shortType": "string",
              "type": "esriFieldTypeString"
            },
            "operator": "stringOperatorIs",
            "valueObj": {
              "isValid": true,
              "type": "unique",
              "value": ""
            },
            "interactiveObj": {
              "prompt": "Select a project below to view",
              "hint": "Select from list"
            },
            "caseSensitive": false
          }
        ],
        "expr": ""
      },
      "icon": ""
    }
  ]
}
```

**Comment by kushu493** [comment]
Scott,

I have attached the updated ISLayers Widget.js file. 
[Widget.zip](https://github.com/Esri/WAB-Image-Services-Widgets/files/412558/Widget.zip)

Copy and paste the Widget.js file to /widgets/ISLayers/ location.

Let me know if your problem is solved and the fix worked.

Regards,

Kushagra

**Comment by sirws** [comment]
Hi Kushagra,

http://52.8.111.163/lidarexplorer2fix/
It does not seem to fix it.  If you swap the primary and secondary layers, it seems to remove the layers from the TOC and map:

![image](https://cloud.githubusercontent.com/assets/793576/17595227/fec1852c-5fa0-11e6-9f90-7033bf82a858.png)

Thanks,
Scott

**Comment by sirws** [comment]
[lidarexplorer2fix.zip](https://github.com/Esri/WAB-Image-Services-Widgets/files/413635/lidarexplorer2fix.zip)

Here is the app code if you would like it for debug...

**Comment by kushu493** [comment]
Scott,

You cannot have two layers with same id in the webmap. That's why i always change the id of topmost layer to primary and layer below it to secondaryLayer. Now because you requested that ids should be same as the original layer Ids for filter to work, i changed them. But it turns out that this is what causing the filter widget along with ISLayers to fail.

I suggest two things seeing your requirement - 
1) Actually there is an option in Layerlist widget to move Layers up/down(basically reorder). You can use it to change the active layer. or
2) I have added the feature of selecting the active layer in ISRenderer widget. So now you can change the layers from ISRenderer.  I have attached the app source with this implementation.
[lidarexplorer2fix.zip](https://github.com/Esri/WAB-Image-Services-Widgets/files/416982/lidarexplorer2fix.zip)


In both the options, ISLayers can be removed from the app. Even the group is not required.

**Comment by sirws** [comment]
Hi Kushagra!

Thanks for the fix.  I am testing it out now.  I am not sure why you have to rename the id's of the layers.  I would think you could keep track internally within WABIS a mapping of which layer is primary and which is secondary without modifying the id of the layers.  For example, in here:
http://pnw.maps.arcgis.com/sharing/rest/content/items/6bfd0ae5d2b24ad7aca62a6927f144c3/data?f=json
You could map id: "Portland_boundary_4955" to "primaryLayer" and "Portland_boundary_4955_7143" to "secondaryLayer".  If the user reorders the secondary layer, you can internally keep track of that, without actually modifying the layerids in the webmap.  We may end up using more WABIS widgets and I am concerned that merely putting in a fix for the ISRenderer widget will not fix the issue when we want to start adding those additional widgets that do rely on ISLayers.

ISLayers is nice because it gave the user the ability to easily manage the visibility of the layer.  In your latest fix, once I start swapping the active layer in the ISRenderer widget, it sets the active layer visible, but leaves the previous one visible too, so once I start applying the filter, it is hard to tell what is going on because both layers are still visible.  The user would have to go to the layer list widget and toggle the visibility off on the secondary layer(s) to make sense of it.

**Comment by sirws** [comment]
This is a better example of the webmap json: http://wadnr.maps.arcgis.com/sharing/rest/content/items/aaf626bc4f9b435199eae80f0bdb7fbb/data?f=json
LayerID's are unique even if the same layer has been added more than once.

**Comment by kushu493** [comment]
Scott,

Webmap will add two same layers but it automatically assigns new Id to the copy. In ISLayers widget, since you want me to preserve the original id of the layer for filter to work, i am actually adding same layer twice with same id. In this case, webmap rejects the copy. 

In the below app, ISLayers now does not assign any id to the layer when it is added to map. So whatever the id of the layer is in the map it will remain the same. You can use swap to change the active layer and it will work. 

Scenario it will fail -
active layer - WA State DSM (Surface) - VALUE IN FIRST DROPDOWN LIST OF ISLayers
secondaryLayer  - WA State DTM (Terrain)  - VALUE IN SECOND DROPDOWN LIST OF ISLayers

Now if you change the first dropdown value/active layer to  WA State DTM (Terrain) this means you are removing  WA State DSM (Surface) from the map and adding one more WA State DTM (Terrain) layer to the map. In this case, the webmap will assign a new id to the layer and your filter wont work on this layer.

So please don't select anything from dropdown. Just use swap button to change the layer order.

You can do customizations on the widget and remove the unnecessary things. In your case, you dont need copy button along with the dropdown list of layers.

The basic idea is that these widgets are generic, if user wants them to function as they want and they can customize it according to their needs. These widgets just lay the foundation, its upto the user how they enhance/modify it.

I am doing the same thing for your app, i am customizing the widget according to your needs.

The enhancement you suggested cannot be incorporated into generic widgets as it is specific to your app.

App - 
[lidarexplorer2fix.zip](https://github.com/Esri/WAB-Image-Services-Widgets/files/419725/lidarexplorer2fix.zip)


Regards,

Kushagra Patel
